version: '3.8'

services:
  node:
    build: ./nodeJS
    container_name: "node"
    restart: always
    tty:  true
    networks:
      - br-net
    volumes:
      - home_js:/ft_transcendence
    ports:
      - 80:80
      - 3000:3000

volumes:
  home_js:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/ft_transcendence

networks:
    br-net:
      name: br-net
      # driver: bridge
      # ipam:
      #   config:
      #    - subnet: 172.16.0.0/28