version: '3.8'

services:
  node:
    build: ./nodeJS
    container_name: "node"
    #    restart: always
    tty:  true
    networks:
      - br-net
    volumes:
<<<<<<< HEAD
      - home_js:/app
=======
      - home_js:/home/leo
>>>>>>> f4be77a (Arch)
    ports:
      - 80:80
      - 3000:3000

volumes:
  home_js:
    driver: local
    driver_opts:
      type: none
      o: bind
<<<<<<< HEAD
      device: ${HOME}/00_myPiscineJS
=======
      device: ${HOME}/00_javaScript
>>>>>>> f4be77a (Arch)

networks:
    br-net:
      name: br-net
      # driver: bridge
      # ipam:
      #   config:
      #    - subnet: 172.16.0.0/28
